#ifndef BAZEL_DEVTOOLS_EXAMPLES_POLYGLOT_CPP_CONTEXT_CURRENT_REPOSITORY_H_
#define BAZEL_DEVTOOLS_EXAMPLES_POLYGLOT_CPP_CONTEXT_CURRENT_REPOSITORY_H_

#include <string_view>

auto CurrentRepository() -> std::string_view;

#endif  // BAZEL_DEVTOOLS_EXAMPLES_POLYGLOT_CPP_CONTEXT_CURRENT_REPOSITORY_H_
