module(
    name = "bazel_devtools",
    version = "0.1.0",
    bazel_compatibility = [">=9.0.0"],
)

bazel_dep(name = "aspect_rules_lint", version = "2.7.2")
bazel_dep(name = "aspect_rules_js", version = "3.4.0")
bazel_dep(name = "aspect_rules_ts", version = "3.10.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_go", version = "0.59.0")
bazel_dep(name = "rules_python", version = "2.2.0")
bazel_dep(name = "rules_rust", version = "0.73.0")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "rules_multitool", version = "1.0.0")
bazel_dep(name = "toolchains_llvm", version = "1.8.0")

bazel_dep(name = "rules_bazel_integration_test", version = "0.37.1", dev_dependency = True)
bazel_dep(name = "rules_testing", version = "0.9.0", dev_dependency = True)

bazel_binaries = use_extension(
    "@rules_bazel_integration_test//:extensions.bzl",
    "bazel_binaries",
    dev_dependency = True,
)
bazel_binaries.download(version_file = "//:.bazelversion")
use_repo(bazel_binaries, "bazel_binaries", "bazel_binaries_bazelisk", "build_bazel_bazel_.bazelversion")

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "actionlint_linux_x86_64",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
exports_files(["actionlint"])
""",
    dev_dependency = True,
    sha256 = "8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8",
    urls = [
        "https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_linux_amd64.tar.gz",
    ],
)

http_archive(
    name = "neovim_linux_x86_64",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
exports_files(["bin/nvim"])
filegroup(name = "dist", srcs = glob(["**"]))
""",
    dev_dependency = True,
    sha256 = "31cf85945cb600d96cdf69f88bc68bec814acbff50863c5546adef3a1bcef260",
    strip_prefix = "nvim-linux-x86_64",
    urls = ["https://github.com/neovim/neovim/releases/download/v0.12.2/nvim-linux-x86_64.tar.gz"],
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.14",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "bazel_devtools_pypi",
    python_version = "3.14",
    requirements_lock = "//:requirements_lock.txt",
)
use_repo(pip, "bazel_devtools_pypi")

multitool = use_extension("@rules_multitool//multitool:extension.bzl", "multitool")
multitool.hub(lockfile = "//:multitool.lock.json")
use_repo(multitool, "multitool")
