local workspace = assert(vim.env.BAZEL_DEVTOOLS_WORKSPACE)

local contracts = {
  { file = "python/greeting.py", marker = "pyrightconfig.json" },
  { file = "cpp/greeting.cc", marker = "compile_commands.json" },
  { file = "rust/greeting.rs", marker = "rust-project.json" },
  { file = "typescript/greeting.ts", marker = "tsconfig.json" },
}

for _, contract in ipairs(contracts) do
  local file = workspace .. "/" .. contract.file
  vim.cmd.edit(vim.fn.fnameescape(file))
  local root = vim.fs.root(0, { contract.marker })
  local expected_root = workspace .. (contract.root and "/" .. contract.root or "")
  assert(root == expected_root, contract.file .. " resolved to unexpected root " .. tostring(root))
  local lines = vim.fn.readfile(root .. "/" .. contract.marker)
  if lines[1] and vim.startswith(lines[1], "// Generated by bazel_devtools") then
    table.remove(lines, 1)
  end
  local decoded = vim.json.decode(table.concat(lines, "\n"))
  assert(type(decoded) == "table", contract.marker .. " is not valid JSON")
end

vim.cmd.quitall({ bang = true })
