load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    deps = ["//:tsconfig"],
)

ts_project(
    name = "greeting",
    srcs = [
        "greeting.ts",
        "greeting_view.tsx",
    ],
    no_emit = True,
    tsconfig = ":tsconfig",
    deps = [
        "//:node_modules/@types/react",
        "//:node_modules/react",
    ],
)
