load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "greeting",
    srcs = [
        "greeting.ts",
        "greeting_view.tsx",
    ],
    extends = "//:tsconfig",
    no_emit = True,
    tsconfig = {},
    deps = [
        "//:node_modules/@types/react",
        "//:node_modules/react",
    ],
)

filegroup(
    name = "editor_excluded",
    srcs = ["editor_excluded.ts"],
    tags = ["no-ide"],
)
