"""Shared TypeScript editor-project metadata helpers."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

TSCONFIG_EDITOR_MARKER = "// Generated by bazel_devtools ide-sync. Edit tsconfig.user.json instead."


def render_editor_tsconfig(sources: list[Path]) -> str:
    """Render the generated root config over the exact Bazel-owned source set."""
    config = {
        "extends": "./tsconfig.user.json",
        "files": [source.as_posix() for source in sources],
    }
    return TSCONFIG_EDITOR_MARKER + "\n" + json.dumps(config, indent=2) + "\n"


def is_generated_editor_tsconfig(content: str) -> bool:
    """Return whether content carries the stable generated-file marker."""
    return content.startswith(TSCONFIG_EDITOR_MARKER + "\n")
